# Generated by Django 3.1.7 on 2021-04-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_internetmagaz', '0002_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
