# Generated by Django 3.1.7 on 2021-04-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_internetmagaz', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='kind_order',
            field=models.IntegerField(),
        ),
    ]
