# Generated by Django 3.1.7 on 2021-04-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_internetmagaz', '0007_mensblouse_menscostume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensblouse',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='menscostume',
            name='photo',
        ),
    ]
