# Generated by Django 3.1.7 on 2021-04-07 13:18

from django.db import migrations, models
import main_internetmagaz.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_internetmagaz', '0008_auto_20210407_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensblouse',
            name='photo',
            field=models.ImageField(default=True, upload_to=main_internetmagaz.models.MensBlouse.get_file_name),
        ),
        migrations.AddField(
            model_name='menscostume',
            name='photo',
            field=models.ImageField(default=True, upload_to=main_internetmagaz.models.MensCostume.get_file_name),
        ),
    ]
